import { ModelProviderMap } from '../types/types';

// 默认模型提供商配置
export const DEFAULT_MODEL_PROVIDERS: ModelProviderMap = {
  BaiZhiCloud: {
    label: 'BaiZhiCloud',
    cn: '百智云',
    icon: 'icon-baizhiyunlogo',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://model-square.app.baizhi.cloud/token',
    defaultBaseUrl: 'https://model-square.app.baizhi.cloud/v1',
  },
  ZhiPu: {
    label: 'ZhiPu',
    cn: '智谱',
    icon: 'icon-zhipuqingyan', // 需要添加对应的图标
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://docs.bigmodel.cn/',
    defaultBaseUrl: 'https://open.bigmodel.cn/api/paas/v4',
  },
  DeepSeek: {
    label: 'DeepSeek',
    cn: 'DeepSeek',
    icon: 'icon-deepseek',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://platform.deepseek.com/api-docs/',
    defaultBaseUrl: 'https://api.deepseek.com/v1',
  },
  Hunyuan: {
    label: 'Hunyuan',
    cn: '腾讯混元',
    icon: 'icon-tengxunhunyuan',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://cloud.tencent.com/document/product/1729/111007',
    defaultBaseUrl: 'https://api.hunyuan.cloud.tencent.com/v1',
  },
  BaiLian: {
    label: 'BaiLian',
    cn: '阿里云百炼',
    icon: 'icon-aliyunbailian',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://help.aliyun.com/zh/model-studio/getting-started/',
    defaultBaseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
  },
  Volcengine: {
    label: 'Volcengine',
    cn: '火山引擎',
    icon: 'icon-huoshanyinqing',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://www.volcengine.com/docs/82379/1182403',
    defaultBaseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
  },
  OpenAI: {
    label: 'OpenAI',
    cn: 'OpenAI',
    icon: 'icon-chatgpt',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://platform.openai.com/docs',
    defaultBaseUrl: 'https://api.openai.com/v1',
  },
  Ollama: {
    label: 'Ollama',
    cn: 'Ollama',
    icon: 'icon-ollama',
    urlWrite: true,
    secretRequired: false,
    customHeader: true,
    modelDocumentUrl: 'https://github.com/ollama/ollama/tree/main/docs',
    defaultBaseUrl: 'http://127.0.0.1:11434',
  },
  SiliconFlow: {
    label: 'SiliconFlow',
    cn: '硅基流动',
    icon: 'icon-a-ziyuan2',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://docs.siliconflow.cn/',
    defaultBaseUrl: 'https://api.siliconflow.cn/v1',
  },
  Moonshot: {
    label: 'Moonshot',
    cn: '月之暗面',
    icon: 'icon-Kim',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://platform.moonshot.cn/docs/',
    defaultBaseUrl: 'https://api.moonshot.cn/v1',
  },
  AzureOpenAI: {
    label: 'AzureOpenAI',
    cn: 'Azure OpenAI',
    icon: 'icon-azure',
    urlWrite: true,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://learn.microsoft.com/en-us/azure/ai-services/openai/',
    defaultBaseUrl: 'https://<resource_name>.openai.azure.com',
  },
  Gemini: {
    label: 'Gemini',
    cn: 'Gemini',
    icon: 'icon-gemini',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://ai.google.dev/gemini-api/docs',
    defaultBaseUrl: 'https://generativelanguage.googleapis.com',
  },
  Qiniu: {
    label: 'Qiniu',
    cn: '七牛云',
    icon: 'icon-qiniuyun',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://developer.qiniu.com/aitokenapi',
    defaultBaseUrl: 'https://api.qnaigc.com/v1',
  },
  // NewAPI: {
  //   label: 'NewAPI',
  //   cn: 'New API',
  //   icon: 'icon-newapi',
  //   urlWrite: true,
  //   secretRequired: true,
  //   customHeader: false,
  //   modelDocumentUrl: '',
  //   defaultBaseUrl: 'http://localhost:3000/v1',
  // },
  // LMStudio: {
  //   label: 'LMStudio',
  //   cn: 'LM Studio',
  //   icon: 'icon-lmstudio',
  //   urlWrite: true,
  //   secretRequired: false,
  //   customHeader: false,
  //   modelDocumentUrl: '',
  //   defaultBaseUrl: 'http://localhost:1234/v1',
  // },
  // Anthropic: {
  //   label: 'Anthropic',
  //   cn: 'Anthropic',
  //   icon: 'icon-anthropic',
  //   urlWrite: false,
  //   secretRequired: true,
  //   customHeader: false,
  //   modelDocumentUrl: 'https://console.anthropic.com/account/keys',
  //   defaultBaseUrl: 'https://api.anthropic.com',
  // },
  // GitHub: {
  //   label: 'GitHub',
  //   cn: 'GitHub Models',
  //   icon: 'icon-github',
  //   urlWrite: false,
  //   secretRequired: true,
  //   customHeader: false,
  //   modelDocumentUrl: 'https://github.com/settings/tokens',
  //   defaultBaseUrl: 'https://models.github.ai/catalog',
  // },
  Yi: {
    label: 'Yi',
    cn: '零一万物',
    icon: 'icon-lingyiwanwu',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://platform.lingyiwanwu.com/docs',
    defaultBaseUrl: 'https://api.lingyiwanwu.com/v1',
  },
  // Baichuan: {
  //   label: 'Baichuan',
  //   cn: '百川智能',
  //   icon: 'icon-baichuan',
  //   urlWrite: false,
  //   secretRequired: true,
  //   customHeader: false,
  //   modelDocumentUrl: 'https://platform.baichuan-ai.com/console/apikey',
  //   defaultBaseUrl: 'https://api.baichuan-ai.com/v1',
  // },
  // Ph8: {
  //   label: 'Ph8',
  //   cn: 'PH8大模型开放平台',
  //   icon: 'icon-ph8',
  //   urlWrite: false,
  //   secretRequired: true,
  //   customHeader: false,
  //   modelDocumentUrl: '',
  //   defaultBaseUrl: 'https://ph8.co/v1',
  // },
  // MiniMax: {
  //   label: 'MiniMax',
  //   cn: 'MiniMax',
  //   icon: 'icon-minimax',
  //   urlWrite: false,
  //   secretRequired: true,
  //   customHeader: false,
  //   modelDocumentUrl: 'https://api.minimax.chat/user-center/basic-information/interface-key',
  //   defaultBaseUrl: 'https://api.minimaxi.com/v1',
  // },
  // Groq: {
  //   label: 'Groq',
  //   cn: 'Groq',
  //   icon: 'icon-groq',
  //   urlWrite: false,
  //   secretRequired: true,
  //   customHeader: false,
  //   modelDocumentUrl: 'https://console.groq.com/keys',
  //   defaultBaseUrl: 'https://api.groq.com/openai/v1',
  // },
  // Together: {
  //   label: 'Together',
  //   cn: 'Together',
  //   icon: 'icon-together',
  //   urlWrite: false,
  //   secretRequired: true,
  //   customHeader: false,
  //   modelDocumentUrl: 'https://api.together.xyz/settings/api-keys',
  //   defaultBaseUrl: 'https://api.together.xyz/v1',
  // },
  // Jina: {
  //   label: 'Jina',
  //   cn: 'Jina',
  //   icon: 'icon-hyperbolic',
  //   urlWrite: false,
  //   secretRequired: true,
  //   customHeader: false,
  //   modelDocumentUrl: '',
  //   defaultBaseUrl: 'https://api.jina.ai/v1',
  // },
  
  CTYun: {
    label: 'CTYun',
    cn: '天翼云息壤',
    icon: 'icon-tianyiyun',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://www.ctyun.cn/products/ctxirang',
    defaultBaseUrl: 'https://wishub-x1.ctyun.cn/v1',
  },
  TencentTI: {
    label: 'TencentTI',
    cn: '腾讯云TI',
    icon: 'icon-tengxunyun',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://cloud.tencent.com/document/product/1772',
    defaultBaseUrl: 'https://api.lkeap.cloud.tencent.com/v1',
  },
  BaiDuQianFan: {
    label: 'BaiDuQianFan',
    cn: '百度云千帆',
    icon: 'icon-baiduyun',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://cloud.baidu.com/doc/index.html',
    defaultBaseUrl: 'https://qianfan.baidubce.com/v2',
  },
  ModelScope: {
    label: 'ModelScope',
    cn: '魔搭社区',
    icon: 'icon-modaGPT',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://modelscope.cn/docs/model-service/API-Inference/intro',
    defaultBaseUrl: 'https://api-inference.modelscope.cn/v1',
  },
  Infini: {
    label: 'Infini',
    cn: '无问芯穹',
    icon: 'icon-infini',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://docs.infini-ai.com/gen-studio/api/maas.html#/operations/chatCompletions',
    defaultBaseUrl: 'https://cloud.infini-ai.com/maas/v1',
  },
  StepFun: {
    label: 'StepFun',
    cn: '阶跃星辰',
    icon: 'icon-step',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://platform.stepfun.com/docs/overview/concept',
    defaultBaseUrl: 'https://api.stepfun.com/v1',
  },
  LanYun: {
    label: 'LanYun',
    cn: '蓝耘科技',
    icon: 'icon-lanyun',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://archive.lanyun.net/#/maas/',
    defaultBaseUrl: 'https://maas-api.lanyun.net/v1',
  },
  AlayaNew: {
    label: 'AlayaNew',
    cn: '九章智算云',
    icon: 'icon-alayanew',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://docs.alayanew.com/docs/modelService/interview?utm_source=cherrystudio',
    defaultBaseUrl: 'https://deepseek.alayanew.com/v1',
  },
  PPIO: {
    label: 'PPIO',
    cn: '欧派云',
    icon: 'icon-ppio',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://docs.cherry-ai.com/pre-basic/providers/ppio?invited_by=JYT9GD&utm_source=github_cherry-studio',
    defaultBaseUrl: 'https://api.ppinfra.com/v3/openai',
  },
  AiHubMix: {
    label: 'AiHubMix',
    cn: 'AiHubMix',
    icon: 'icon-aihubmix',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://doc.aihubmix.com/',
    defaultBaseUrl: 'https://aihubmix.com/v1',
  },
  OcoolAI: {
    label: 'OcoolAI',
    cn: 'OcoolAI',
    icon: 'icon-ocoolai',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://docs.ocoolai.com/',
    defaultBaseUrl: 'https://api.ocoolai.com/v1',
  },
  DMXAPI: {
    label: 'DMXAPI',
    cn: 'DMXAPI',
    icon: 'icon-DMXAPI',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://dmxapi.cn/models.html#code-block',
    defaultBaseUrl: 'https://www.dmxapi.cn/v1',
  },
  BurnCloud: {
    label: 'BurnCloud',
    cn: 'BurnCloud',
    icon: 'icon-burncloud',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://ai.burncloud.com/docs',
    defaultBaseUrl: 'https://ai.burncloud.com/v1',
  },
  // Grok: {
  //   label: 'Grok',
  //   cn: 'Grok',
  //   icon: 'icon-grok',
  //   urlWrite: false,
  //   secretRequired: true,
  //   customHeader: false,
  //   modelDocumentUrl: 'https://docs.x.ai/',
  //   defaultBaseUrl: 'https://api.x.ai/v1',
  // },
  Nvidia: {
    label: 'Nvidia',
    cn: '英伟达',
    icon: 'icon-yingweida',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://docs.api.nvidia.com/nim/reference/llm-apis',
    defaultBaseUrl: 'https://integrate.api.nvidia.com/v1',
  },
  TokenFlux: {
    label: 'TokenFlux',
    cn: 'TokenFlux',
    icon: 'icon-tokenflux',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://tokenflux.ai/docs',
    defaultBaseUrl: 'https://tokenflux.ai/v1',
  },
  AI302: {
    label: 'AI302',
    cn: '302.AI',
    icon: 'icon-a-302ai',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://302ai.apifox.cn/api-147522039',
    defaultBaseUrl: 'https://api.302.ai/v1',
  },
  Cephalon: {
    label: 'Cephalon',
    cn: 'Cephalon',
    icon: 'icon-cephalon',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://cephalon.cloud/apitoken/1864244127731589124',
    defaultBaseUrl: 'https://cephalon.cloud/user-center/v1/model',
  },
  OpenRouter: {
    label: 'OpenRouter',
    cn: 'OpenRouter',
    icon: 'icon-openrouter',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://openrouter.ai/docs/quick-start',
    defaultBaseUrl: 'https://openrouter.ai/api/v1',
  },
  Fireworks: {
    label: 'Fireworks',
    cn: 'Fireworks',
    icon: 'icon-fireworks',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://docs.fireworks.ai/getting-started/introduction',
    defaultBaseUrl: 'https://api.fireworks.ai/inference/v1',
  },
  Mistral: {
    label: 'Mistral',
    cn: 'Mistral',
    icon: 'icon-Mistral',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://docs.mistral.ai',
    defaultBaseUrl: 'https://api.mistral.ai/v1',
  },
  Perplexity: {
    label: 'Perplexity',
    cn: 'Perplexity',
    icon: 'icon-perplexity',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://docs.perplexity.ai/home',
    defaultBaseUrl: 'https://api.perplexity.ai',
  },
  Hyperbolic: {
    label: 'Hyperbolic',
    cn: 'Hyperbolic',
    icon: 'icon-hyperbolic',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://docs.hyperbolic.xyz',
    defaultBaseUrl: 'https://api.hyperbolic.xyz/v1',
  },
  // VoyageAI: {
  //   label: 'VoyageAI',
  //   cn: 'Voyage AI',
  //   icon: 'icon-voyageai',
  //   urlWrite: false,
  //   secretRequired: true,
  //   customHeader: false,
  //   modelDocumentUrl: '',
  //   defaultBaseUrl: 'https://api.voyageai.com/v1',
  // },
  // Poe: {
  //   label: 'Poe',
  //   cn: 'Poe',
  //   icon: 'icon-poe',
  //   urlWrite: false,
  //   secretRequired: true,
  //   customHeader: false,
  //   modelDocumentUrl: '',
  //   defaultBaseUrl: 'https://api.poe.com/v1',
  // },
  Other: {
    label: 'Other',
    cn: '其他',
    icon: 'icon-a-AIshezhi',
    urlWrite: true,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: '',
    defaultBaseUrl: '',
  },
};
